/**
 * encode-data.mjs — "light obfuscation" build step.
 *
 * Reads the plain JSON data from backend/data/ (the source of truth you keep
 * editing) and writes a single obfuscated blob to frontend/src/lib/data.enc.js.
 * The browser decodes it at runtime (see frontend/src/lib/codec.js).
 *
 * This is deliberately LIGHT: it stops the raw JSON being copy-paste-readable
 * from the source files / DevTools. A determined researcher can still decode it.
 * Importantly it does NOT change your update workflow — you still edit the
 * plain JSON / spreadsheet, then rebuild; this script re-encodes automatically.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA_DIR = path.join(ROOT, 'backend', 'data');
const OUT_FILE = path.join(ROOT, 'frontend', 'src', 'lib', 'data.enc.js');

// Key is kept simple on purpose (light obfuscation).
const KEY = 'mistfall-2026-hunter';

const FILES = [
  'classes', 'gear', 'gem_catalog', 'affixes',
  'affix_registry', 'prices', 'armor', 'gems'
];

function encodePack(obj) {
  const json = JSON.stringify(obj);
  const bytes = Buffer.from(json, 'utf8');
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = bytes[i] ^ KEY.charCodeAt(i % KEY.length);
  }
  return bytes.toString('base64');
}

const pack = {};
for (const f of FILES) {
  pack[f] = JSON.parse(readFileSync(path.join(DATA_DIR, f + '.json'), 'utf8'));
}

const out =
  '// AUTO-GENERATED by scripts/encode-data.mjs — do not edit by hand.\n' +
  '// Run `npm run build` (or `node scripts/encode-data.mjs`) to regenerate.\n' +
  'export const DATA_ENC = "' + encodePack(pack) + '";\n';

mkdirSync(path.dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, out, 'utf8');

console.log('encode-data: wrote', path.relative(ROOT, OUT_FILE), '(' + out.length + ' bytes)');