// AUTO-GENERATED by scripts/fetch-affix-icons.mjs — do not edit by hand.
import AAegis from '../assets/icons/affixes/Aegis.webp';
import ABlessing from '../assets/icons/affixes/Blessing.webp';
import ABrotherhood from '../assets/icons/affixes/Brotherhood.webp';
import ABulwark from '../assets/icons/affixes/Bulwark.webp';
import ABurst from '../assets/icons/affixes/Burst.webp';
import ACreation from '../assets/icons/affixes/Creation.webp';
import ACurse from '../assets/icons/affixes/Curse.webp';
import ADeft from '../assets/icons/affixes/Deft.webp';
import ADistantWard from '../assets/icons/affixes/Distant_Ward.webp';
import AEloquence from '../assets/icons/affixes/Eloquence.webp';
import AElusive from '../assets/icons/affixes/Elusive.webp';
import AEthereal from '../assets/icons/affixes/Ethereal.webp';
import AFervid from '../assets/icons/affixes/Fervid.webp';
import AFervor from '../assets/icons/affixes/Fervor.webp';
import AFocused from '../assets/icons/affixes/Focused.webp';
import AIronHelmet from '../assets/icons/affixes/Iron_Helmet.webp';
import ARanged from '../assets/icons/affixes/Ranged.webp';
import AResilience from '../assets/icons/affixes/Resilience.webp';
import ASeamless from '../assets/icons/affixes/Seamless.webp';
import ASeeker from '../assets/icons/affixes/Seeker.webp';
import ASkyPiercer from '../assets/icons/affixes/Sky_Piercer.webp';
import ASmiting from '../assets/icons/affixes/Smiting.webp';
import ASpiritShield from '../assets/icons/affixes/Spirit_Shield.webp';
import AStoic from '../assets/icons/affixes/Stoic.webp';
import AStrife from '../assets/icons/affixes/Strife.webp';
import ASwift from '../assets/icons/affixes/Swift.webp';
import ATenacious from '../assets/icons/affixes/Tenacious.webp';
import AUnyielding from '../assets/icons/affixes/Unyielding.webp';
import AValor from '../assets/icons/affixes/Valor.webp';
import AVitality from '../assets/icons/affixes/Vitality.webp';
import AWealth from '../assets/icons/affixes/Wealth.webp';
import AWrath from '../assets/icons/affixes/Wrath.webp';
export const AFFIX_ICONS = {
  'Aegis': AAegis,
  'Blessing': ABlessing,
  'Brotherhood': ABrotherhood,
  'Bulwark': ABulwark,
  'Burst': ABurst,
  'Creation': ACreation,
  'Curse': ACurse,
  'Deft': ADeft,
  'Distant Ward': ADistantWard,
  'Eloquence': AEloquence,
  'Elusive': AElusive,
  'Ethereal': AEthereal,
  'Fervid': AFervid,
  'Fervor': AFervor,
  'Focused': AFocused,
  'Iron Helmet': AIronHelmet,
  'Ranged': ARanged,
  'Resilience': AResilience,
  'Seamless': ASeamless,
  'Seeker': ASeeker,
  'Sky Piercer': ASkyPiercer,
  'Smiting': ASmiting,
  'Spirit Shield': ASpiritShield,
  'Stoic': AStoic,
  'Strife': AStrife,
  'Swift': ASwift,
  'Tenacious': ATenacious,
  'Unyielding': AUnyielding,
  'Valor': AValor,
  'Vitality': AVitality,
  'Wealth': AWealth,
  'Wrath': AWrath,
};
