/**
 * Mistfall Hunter Build Optimizer — browser (static) port of backend/optimizer.js
 * and backend/pricing.js.
 *
 * The original ran as a Node/Express service reading JSON from disk and exposing a
 * REST API. For free static hosting (GitHub/Cloudflare Pages) we run the exact same
 * MILP engine directly in the browser: the JSON data is bundled at build time and the
 * price index is built once in memory. Exports mirror the old /api/* responses so the
 * React UI calls these functions directly instead of fetch().
 */

import solver from 'javascript-lp-solver';
import { decodePack } from './codec';
import { DATA_ENC } from './data.enc.js';

// Decode the obfuscated data blob at runtime. The plain JSON in backend/data/
// is the source of truth; data.enc.js is generated by scripts/encode-data.mjs.
const P = decodePack(DATA_ENC);

const DATA = {
  classes: P.classes,
  gear: P.gear,
  gemCatalog: P.gem_catalog,
  affixes: P.affixes,
  affixRegistry: P.affix_registry
};
const PRICES = P.prices;
const ARMOR = P.armor;
const GEMS = P.gems;

function loadData() { return DATA; }

function validAffixSet() {
  const { affixes, affixRegistry } = DATA;
  const set = new Set();
  for (const a of affixes) if (a.name) set.add(a.name);
  for (const a of affixRegistry) if (a.name) set.add(a.name);
  return set;
}

// ---- Pricing (port of backend/pricing.js) ----
const DEFAULT_ARMOR_COST = 500;
const DEFAULT_WEAPON_COST = 1500;
const DEFAULT_GEM_COST = 150;

const WEAPON_SLOTS = new Set(['Weapon', 'Mace', 'Catalyst', 'Greatsword', 'Bow', 'Staff', 'Dagger', 'Dual Blades', 'Hammer', 'Sword and Shield', 'Polearm and Shield']);

function buildPriceIndex() {
  const priceByName = {};
  for (const p of PRICES) {
    if (p && p.name && p.price != null) priceByName[p.name] = Number(p.price);
  }
  for (const a of ARMOR) {
    if (a && a.name && a.recommendedPrice != null && priceByName[a.name] == null) {
      priceByName[a.name] = Number(a.recommendedPrice);
    }
  }
  const gemPriceByAffix = {};
  for (const g of GEMS) {
    if (g == null || g.gemLevel == null || !Array.isArray(g.affixes)) continue;
    const names = g.affixes.map(a => (a && a.name) || '').filter(Boolean).sort();
    const key = g.gemLevel + '|' + names.join('|');
    let price = DEFAULT_GEM_COST;
    if (g.recommendedPrice != null) price = Number(g.recommendedPrice);
    else if (g.minPrice != null && g.maxPrice != null) price = Math.round((Number(g.minPrice) + Number(g.maxPrice)) / 2);
    gemPriceByAffix[key] = price;
  }
  return { priceByName, armorPrice: priceByName, gemPriceByAffix, config: { DEFAULT_ARMOR_COST, DEFAULT_WEAPON_COST, DEFAULT_GEM_COST } };
}

function gearCost(index, gearName, slot) {
  if (index.priceByName[gearName] != null) return index.priceByName[gearName];
  return WEAPON_SLOTS.has(slot) ? DEFAULT_WEAPON_COST : DEFAULT_ARMOR_COST;
}

function gemCost(index, tier, affix1, affix2) {
  const names = [affix1, affix2].filter(Boolean).sort();
  const key = tier + '|' + names.join('|');
  const p = index.gemPriceByAffix[key];
  return p != null ? p : DEFAULT_GEM_COST;
}

// Built once when the module loads.
const PRICE_INDEX = buildPriceIndex();

// ---- Optimizer constants (identical to backend/optimizer.js) ----
const RARITY_CAPACITY = { Common: 1, Rare: 2, Epic: 3, Legendary: 5, Holy: 6 };

const WEAPONS_BY_CLASS = {
  Blackarrow: ['Weapon'],
  Mercenary: ['Weapon'],
  Seer: ['Mace', 'Catalyst'],
  Shadowstrix: ['Weapon'],
  Sorcerer: ['Weapon'],
  'Withered Knight': ['Weapon']
};

const ARMOR_SLOTS = ['Head', 'Chest', 'Gloves', 'Pants', 'Boots'];
const ACCESSORY_SLOTS = ['Ring', 'Necklace'];
const SLOT_ORDER = ['Head', 'Chest', 'Gloves', 'Pants', 'Boots', 'Ring', 'Necklace', 'Weapon', 'Mace', 'Catalyst'];

const WINES = {
  'Wine 1': { name: 'Mortal Tonic', label: 'Lv 1: Mortal Tonic', cap: 2, stacking: false, maxStack: 1, cost: 0, desc: 'Level 1 Wine — 2 unique affixes (+1 level each)' },
  'Wine 2': { name: "Hero's Ale", label: "Lv 2: Hero's Ale", cap: 4, stacking: false, maxStack: 1, cost: 150, desc: 'Level 2 Wine — 4 unique affixes (+1 level each)' },
  'Wine 3': { name: 'Warblood', label: 'Lv 3: Warblood', cap: 6, stacking: true, maxStack: 2, cost: 270, desc: 'Level 3 Wine — 6 affixes total (can pick up to two affixes twice)' },
  'Wine 4': { name: "God's Brew", label: "Lv 4: God's Brew", cap: 8, stacking: true, maxStack: 2, cost: 530, desc: 'Level 4 Wine — 8 affixes total (can pick up to four affixes twice)' }
};

const WINE_OPTIONS = [
  { key: null, name: null, label: null, cap: 0, maxStack: 0, cost: 0 },
  { key: 'Wine 1', name: 'Mortal Tonic', label: 'Lv 1: Mortal Tonic', cap: 2, maxStack: 1, cost: 0 },
  { key: 'Wine 2', name: "Hero's Ale", label: "Lv 2: Hero's Ale", cap: 4, maxStack: 1, cost: 150 },
  { key: 'Wine 3', name: 'Warblood', label: 'Lv 3: Warblood', cap: 6, maxStack: 2, cost: 270 },
  { key: 'Wine 4', name: "God's Brew", label: "Lv 4: God's Brew", cap: 8, maxStack: 2, cost: 530 }
];

const SOL_LIMIT = 60;
const RANK_BUDGET = 4000;
const MAX_COMBINED_LEVEL = 40;

function poolFor(gear, className, slot) {
  if (ACCESSORY_SLOTS.includes(slot)) return gear.filter(v => v.class === 'All' && v.slot === slot);
  return gear.filter(v => v.class === className && v.slot === slot);
}

function compatibleGems(gemCatalog, sock) {
  const circle = sock.shape === 'Circle' || sock.shape === 'Circle/Swirl';
  return gemCatalog.filter(g => (circle || g.shape === sock.shape) && g.tier <= sock.tier);
}

function assists(need, a1, a2) {
  return (a1 && need[a1] > 0) || (a2 && need[a2] > 0);
}

function buildCore(className, weapon, wine, targets, rarityPref) {
  rarityPref = rarityPref || null;
  const { gear, gemCatalog } = loadData();
  const priceIndex = PRICE_INDEX;

  const weapons = WEAPONS_BY_CLASS[className];
  if (!weapons) return { error: 'Unknown class: ' + className };
  const weaponSlot = weapon;
  if (!weapons.includes(weapon)) {
    return { error: className + ' does not use weapon "' + weapon + '". Options: ' + weapons.join(', ') };
  }

  const forcedAcc = (rarityPref && (rarityPref.Ring || rarityPref.Necklace)) ? ACCESSORY_SLOTS.filter(s => rarityPref[s]) : [];
  const mandatorySlots = ARMOR_SLOTS.concat([weaponSlot]).concat(forcedAcc);
  const allSlots = ARMOR_SLOTS.concat([weaponSlot]).concat(ACCESSORY_SLOTS);

  if (!targets || targets.length === 0) return { error: 'Select at least one affix.' };

  const need = {};
  let combined = 0;
  for (const t of targets) {
    const lvl = Math.max(1, Math.min(MAX_COMBINED_LEVEL, Math.floor(t.level || 1)));
    need[t.affix] = (need[t.affix] || 0) + lvl;
    combined += lvl;
  }
  if (combined > MAX_COMBINED_LEVEL) return { error: 'Combined affix level ' + combined + ' exceeds the max of ' + MAX_COMBINED_LEVEL + '.' };

  let options;
  if (wine && wine.name) {
    const opt = WINE_OPTIONS.find(o => o.key === wine.name) || WINE_OPTIONS.find(o => o.name === wine.name);
    if (!opt) return { error: 'Unknown wine: ' + wine.name };
    options = [opt];
  } else {
    options = WINE_OPTIONS;
  }

  const reachable = new Set();
  for (const s of allSlots) {
    for (const v of poolFor(gear, className, s)) {
      if (v.built_in_affix) reachable.add(v.built_in_affix);
      for (const sock of v.sockets) {
        for (const g of compatibleGems(gemCatalog, sock)) {
          if (g.affix1) reachable.add(g.affix1);
          if (g.affix2) reachable.add(g.affix2);
        }
      }
    }
  }
  const unreachable = Object.keys(need).filter(a => !reachable.has(a) && need[a] > 2);
  if (unreachable.length) {
    return { error: 'Cannot reach affix(es): ' + unreachable.join(', ') + ' with ' + className + ' ' + weaponSlot + '.' };
  }

  for (const s of mandatorySlots) {
    if (poolFor(gear, className, s).length === 0) {
      return { error: 'No gear found for slot "' + s + '" for class ' + className + '.' };
    }
  }

  if (rarityPref) {
    for (const s of mandatorySlots) {
      const want = rarityPref[s];
      if (want && !poolFor(gear, className, s).some(v => v.rarity === want)) {
        return { error: 'No ' + want + ' ' + s + ' gear found for ' + className + '.' };
      }
    }
  }

  let best = null;
  for (const opt of options) {
    const { base } = buildModel(gear, gemCatalog, priceIndex, className, weaponSlot, mandatorySlots, allSlots, need, opt, rarityPref);
    const res = solveOnce(base);
    if (!res || !res.feasible) continue;
    const gearGem = costOf(res, base);
    const total = gearGem + opt.cost;
    if (!best || total < best.total) best = { opt, gearGemCost: gearGem, total };
  }

  if (!best) {
    return { error: 'No ' + className + ' ' + weaponSlot + ' build satisfies the selected affix levels. Try lowering a level or choosing different affixes.' };
  }

  const { base: winnerBase, info } = buildModel(gear, gemCatalog, priceIndex, className, weaponSlot, mandatorySlots, allSlots, need, best.opt, rarityPref);
  return { need, combined, winnerBase, info, best, weaponSlot, priceIndex };
}

function generateBuild(className, weapon, wine, targets, rarityPref) {
  rarityPref = rarityPref || null;
  const core = buildCore(className, weapon, wine, targets, rarityPref);
  if (core.error) return { error: core.error };
  const { need, combined, winnerBase, info, best, weaponSlot, priceIndex } = core;
  const ranked = solveRanked(winnerBase, info, RANK_BUDGET);
  // Add legendary/holy swap-out alternatives (stock-friendly variety), merged in,
  // deduped by gear set, and re-sorted by cost.
  const knownKeys = new Set(ranked.map(sol => buildSetKey(sol.slots)));
  const extras = ranked.length ? legendaryVariants(winnerBase, info, ranked[0], knownKeys, 18, 3000) : [];
  // Full-legendary case: sweep ALL distinct legendary gear combinations.
  const isFullLegend = ranked.length > 0 && ranked[0].slots.every(s => !s.gear || s.rarity === 'Legendary' || s.rarity === 'Holy');
  const enumSols = isFullLegend ? legendaryEnumeration(winnerBase, info, ranked[0].slots, knownKeys, 60, 6000) : [];
  // Merge + dedupe by gear set (each gear set appears once; gems auto-optimized).
  const dedup = new Map();
  for (const sol of ranked.concat(extras, enumSols)) {
    const key = buildSetKey(sol.slots);
    if (!dedup.has(key)) dedup.set(key, sol);
  }
  const allSols = [...dedup.values()].sort((a, b) => a.cost - b.cost).slice(0, 60);

  const rankWin = best.opt;
  const wineLabel = rankWin.label;
  const wineName = rankWin.name;
  const wineKey = rankWin.key;
  const wineCost = rankWin.cost;

  const builds = allSols.map(sol => ({
    slots: sol.slots,
    wineGrants: sol.wineGrants,
    wine: wineLabel,
    wineKey,
    wineName,
    wineCost,
    cost: sol.cost + wineCost,
    capacityWarnings: sol.capacityWarnings
  }));

  return {
    className,
    weapon: weaponSlot,
    wine: {
      key: wineKey,
      name: wineName,
      label: wineLabel,
      cap: rankWin.cap,
      maxStack: rankWin.maxStack,
      cost: wineCost,
      grants: builds.length ? builds[0].wineGrants : []
    },
    targetAffixes: Object.keys(need).map(k => ({ affix: k, level: need[k] })),
    combinedLevel: combined,
    totalBuilds: builds.length,
    pricing: priceIndex.config,
    builds
  };
}

function buildSetKey(slots) {
  // Variant-level key: gear item, rarity, socket shapes and chosen gems — two
  // builds only dedupe when they are truly the same loadout.
  return JSON.stringify((slots || []).map(s => ({
    slot: s.slot, gear: s.gear || '', rar: s.rarity || '',
    sk: (s.sockets || []).map(x => x.shape + '#' + x.tier).join(','),
    g: (s.gems || []).map(g => g ? ((g.affix1 || '') + '/' + (g.affix2 || '')) : '').join(',')
  })));
}

function generateMoreBuilds(className, weapon, wine, targets, rarityPref, seenKeys, count, minCost, budgetMs) {
  rarityPref = rarityPref || null;
  const core = buildCore(className, weapon, wine, targets, rarityPref);
  if (core.error) return { error: core.error };
  const { need, combined, winnerBase, info, best, weaponSlot, priceIndex } = core;
  const modelBase = JSON.parse(JSON.stringify(winnerBase));
  if (minCost) {
    const floorVal = Math.max(1, minCost - (best.opt.cost || 0));
    modelBase.constraints.floormin = { min: floorVal };
    for (const id of Object.keys(modelBase.variables)) {
      const c = modelBase.variables[id].cost || 0;
      if (c) modelBase.variables[id].floormin = c;
    }
  }
  const next = solveRanked(modelBase, info, budgetMs || 3000, new Set(seenKeys || []), count || 5);
  const wineLabel = best.opt.label;
  const wineName = best.opt.name;
  const wineKey = best.opt.key;
  const wineCost = best.opt.cost;
  const builds = next.map(sol => ({
    slots: sol.slots,
    wineGrants: sol.wineGrants,
    wine: wineLabel,
    wineKey,
    wineName,
    wineCost,
    cost: sol.cost + wineCost,
    capacityWarnings: sol.capacityWarnings
  }));
  return {
    className,
    weapon: weaponSlot,
    wine: { key: wineKey, name: wineName, label: wineLabel, cap: best.opt.cap, maxStack: best.opt.maxStack, cost: wineCost, grants: builds.length ? builds[0].wineGrants : [] },
    targetAffixes: Object.keys(need).map(k => ({ affix: k, level: need[k] })),
    combinedLevel: combined,
    totalBuilds: builds.length,
    pricing: priceIndex.config,
    builds
  };
}

function buildModel(gear, gemCatalog, priceIndex, className, weaponSlot, mandatorySlots, allSlots, need, opt, rarityPref) {
  const info = {};
  const base = { optimize: 'cost', opType: 'min', constraints: {}, variables: {}, ints: {} };

  for (const s of allSlots) {
    const isMandatory = mandatorySlots.includes(s);
    const variants = poolFor(gear, className, s).filter(v => !rarityPref || !rarityPref[s] || v.rarity === rarityPref[s]);
    base.constraints['slot_' + s] = { min: isMandatory ? 1 : 0, max: 1 };

    variants.forEach((v, vi) => {
      const id = 'g_' + s + '_' + vi;
      const cost = gearCost(priceIndex, v.gear, v.slot);
      const varObj = { cost };
      varObj['slot_' + s] = 1;
      if (v.built_in_affix && need[v.built_in_affix] > 0) {
        varObj['afx_' + v.built_in_affix] = (varObj['afx_' + v.built_in_affix] || 0) + 1;
      }
      base.variables[id] = varObj;
      base.ints[id] = 1;
      info[id] = { kind: 'gear', slot: s, variant: v, cost };
    });

    variants.forEach((v, vi) => {
      v.sockets.forEach((sock, si) => {
        const scName = 'sc_' + s + '_' + vi + '_' + si;
        base.constraints[scName] = { max: 0 };
        const gid = 'g_' + s + '_' + vi;
        base.variables[gid][scName] = -1;

        const opts = compatibleGems(gemCatalog, sock).filter(g => assists(need, g.affix1, g.affix2));
        opts.forEach((g, gi) => {
          const hid = 'h_' + s + '_' + vi + '_' + si + '_' + gi;
          const cost = gemCost(priceIndex, g.tier, g.affix1, g.affix2);
          const hObj = { cost };
          hObj[scName] = 1;
          if (g.affix1 && need[g.affix1] > 0) hObj['afx_' + g.affix1] = (hObj['afx_' + g.affix1] || 0) + 1;
          if (g.affix2 && need[g.affix2] > 0) hObj['afx_' + g.affix2] = (hObj['afx_' + g.affix2] || 0) + 1;
          base.variables[hid] = hObj;
          base.ints[hid] = 1;
          info[hid] = { kind: 'gem', slot: s, variant: v, socket: sock, socketIndex: si, gem: g, cost };
        });
      });
    });
  }

  for (const a of Object.keys(need)) {
    base.constraints['afx_' + a] = { min: need[a] };
  }

  if (opt.cap > 0) {
    base.constraints.wine_budget = { max: opt.cap };
    for (const a of Object.keys(need)) {
      const wid = 'w_' + a;
      base.variables[wid] = { ['afx_' + a]: 1, wine_budget: 1, ['wmax_' + a]: 1 };
      base.ints[wid] = 1;
      base.constraints['wmax_' + a] = { max: opt.maxStack };
      info[wid] = { kind: 'wine', affix: a };
    }
  }

  return { base, info };
}

function solveOnce(base) {
  const model = JSON.parse(JSON.stringify(base));
  try { return solver.Solve(model); } catch (e) { return null; }
}

function costOf(res, model) {
  let total = 0;
  for (const name of Object.keys(model.variables)) {
    if (res[name] && res[name] > 0.0001) total += res[name] * (model.variables[name].cost || 0);
  }
  return Math.round(total);
}

// Legendary swap-out pass: because legendary gear is often out of stock, surface
// alternatives that deliberately AVOID the legendary/holy items in the cheapest
// build. For each unique legendary item name used there, re-solve with that item
// fully excluded and collect the result as an extra option.
function legendaryVariants(base, info, refSol, knownKeys, maxExtras, budgetMs) {
  const legendaryNames = new Set();
  for (const sl of refSol.slots) {
    if (sl.gear && (sl.rarity === 'Legendary' || sl.rarity === 'Holy')) legendaryNames.add(sl.gear);
  }
  const extras = [];
  const extrasSeen = new Set();
  const tStart = Date.now();
  for (const name of legendaryNames) {
    if (extras.length >= maxExtras || (Date.now() - tStart) > budgetMs) break;
    // Build an exclusion model that forbids every variant of this item name.
    const baseModel = JSON.parse(JSON.stringify(base));
    let ci = 0;
    for (const id of Object.keys(info)) {
      const i = info[id];
      if (i && i.kind === 'gear' && i.variant.gear === name) {
        const cname = 'exclx' + (ci++);
        baseModel.constraints[cname] = { max: 0 };
        if (!baseModel.variables[id]) baseModel.variables[id] = { cost: i.cost || 0 };
        baseModel.variables[id][cname] = 1;
        baseModel.ints[id] = 1;
      }
    }
    if (ci === 0) continue;

    // Collect up to 3 distinct gear sets that avoid this item (gear-diverse).
    const cuts = [];
    for (let k = 0; k < 3 && extras.length < maxExtras && (Date.now() - tStart) < budgetMs; k++) {
      const model = JSON.parse(JSON.stringify(baseModel));
      cuts.forEach((c, ci2) => {
        const cn = 'exclcut_' + ci2;
        model.constraints[cn] = { max: c.max };
        for (const id of c.vars) {
          if (!model.variables[id]) model.variables[id] = { cost: (info[id] ? info[id].cost : 0) };
          model.variables[id][cn] = 1;
          model.ints[id] = 1;
        }
      });
      let res;
      try { res = solver.Solve(model); } catch (e) { break; }
      if (!res || !res.feasible) break;
      const chosen = Object.keys(res).filter(k =>
        !['feasible', 'result', 'bounded', 'isIntegral', 'fractional'].includes(k) && res[k] >= 0.999);
      const gearVars = chosen.filter(k => info[k] && info[k].kind === 'gear');
      cuts.push({ vars: gearVars.length ? gearVars : chosen, max: (gearVars.length ? gearVars : chosen).length - 1 });
      const sol = decode(chosen, info, res);
      const key = buildSetKey(sol.slots);
      if (knownKeys.has(key) || extrasSeen.has(key)) continue;
      extrasSeen.add(key);
      extras.push(sol);
    }
  }
  return extras;
}

// Full-legendary enumeration: the cheapest build is ALL Legendary/Holy. Most slots
// have exactly ONE legendary item name (variants of it), so the real variety lives
// in the few slots with multiple names (Ring, Necklace, some weapons). We enumerate
// EVERY distinct name combination (product), solving only a reduced legendary-only
// model per combo so gems/wine are still auto-optimized — fast AND complete.
function legendaryEnumeration(base, info, refSlots, knownKeys, maxCombos, budgetMs) {
  // Legend-only reduced model: only legendary/holy gear variables remain.
  const modelBase = JSON.parse(JSON.stringify(base));
  let ci = 0;
  for (const id of Object.keys(info)) {
    const i = info[id];
    if (i && i.kind === 'gear' && i.variant.rarity !== 'Legendary' && i.variant.rarity !== 'Holy') {
      const cname = 'lgonly' + (ci++);
      modelBase.constraints[cname] = { max: 0 };
      if (!modelBase.variables[id]) modelBase.variables[id] = { cost: i.cost || 0 };
      modelBase.variables[id][cname] = 1;
      modelBase.ints[id] = 1;
    }
  }

  // Unique legendary item NAMES per slot (from the reference build's slots).
  const perSlotNames = {};
  for (const sl of refSlots) {
    if (!sl || !sl.gear) continue;
    const names = new Set();
    for (const id of Object.keys(info)) {
      const i = info[id];
      if (i && i.kind === 'gear' && i.slot === sl.slot &&
          (i.variant.rarity === 'Legendary' || i.variant.rarity === 'Holy')) names.add(i.variant.gear);
    }
    if (names.size) perSlotNames[sl.slot] = [...names];
  }

  const variableSlots = Object.keys(perSlotNames).filter(s => perSlotNames[s].length > 1);
  if (variableSlots.length === 0) return []; // no variety to enumerate

  let combos = [{}];
  for (const s of variableSlots) {
    const next = [];
    for (const c of combos) {
      for (const n of perSlotNames[s]) next.push({ ...c, [s]: n });
    }
    combos = next;
  }
  if (combos.length > maxCombos) combos = combos.slice(0, maxCombos);

  const results = [];
  const seen = new Set(knownKeys);
  const tStart = Date.now();
  for (const combo of combos) {
    if (results.length >= maxCombos || (Date.now() - tStart) > budgetMs) break;
    const model = JSON.parse(JSON.stringify(modelBase));
    let mn = 0;
    for (const s of variableSlots) {
      const chosen = combo[s];
      for (const id of Object.keys(info)) {
        const i = info[id];
        if (i && i.kind === 'gear' && i.slot === s && i.variant.gear !== chosen) {
          const cn = 'mn' + (mn++);
          model.constraints[cn] = { max: 0 };
          if (!model.variables[id]) model.variables[id] = { cost: i.cost || 0 };
          model.variables[id][cn] = 1;
          model.ints[id] = 1;
        }
      }
    }
    let res;
    try { res = solver.Solve(model); } catch (e) { continue; }
    if (!res || !res.feasible) continue;
    const chosenVars = Object.keys(res).filter(k =>
      !['feasible', 'result', 'bounded', 'isIntegral', 'fractional'].includes(k) && res[k] >= 0.999);
    const sol = decode(chosenVars, info, res);
    const key = buildSetKey(sol.slots);
    if (seen.has(key)) continue;
    seen.add(key);
    results.push(sol);
  }
  return results;
}

function solveRanked(base, info, budgetMs, seenIn, maxResults) {
  const cuts = [];
  const solutions = [];
  const seen = seenIn || new Set();
  const tStart = Date.now();
  const limit = maxResults || SOL_LIMIT;
  const itCap = limit * 6 + (seenIn ? seenIn.size * 2 : 0);
  for (let it = 0; it < itCap && solutions.length < limit && (Date.now() - tStart) < budgetMs; it++) {
    const model = JSON.parse(JSON.stringify(base));
    cuts.forEach((c, ci) => {
      const cname = 'cut_' + ci;
      model.constraints[cname] = { max: c.max };
      for (const id of c.vars) {
        if (!model.variables[id]) model.variables[id] = { cost: (info[id] ? info[id].cost : 0) };
        model.variables[id][cname] = 1;
        model.ints[id] = 1;
      }
    });

    let res;
    try { res = solver.Solve(model); } catch (e) { break; }
    if (!res || !res.feasible) break;

    const chosen = Object.keys(res).filter(k =>
      !['feasible', 'result', 'bounded', 'isIntegral', 'fractional'].includes(k) && res[k] >= 0.999);

    // Diversity: force each NEXT build to change at least one GEAR item (not just
    // a gem), so the list shows genuinely different gear combinations.
    // Diversity: force each NEXT build to change at least one GEAR NAME (not just
    // a different socket variant of the same item), so the list shows genuinely
    // different gear combinations, climbing toward rarer/more expensive sets.
    // Diversity: force each NEXT build to change at least one GEAR item (not just
    // a gem), so the list shows genuinely different gear combinations.
    const gearVars = chosen.filter(k => info[k] && info[k].kind === 'gear');
    const cutVars = (gearVars.length ? gearVars : chosen);
    cuts.push({ vars: cutVars, max: cutVars.length - 1 });

    const sol = decode(chosen, info, res);
    const key = buildSetKey(sol.slots);
    if (seen.has(key)) continue;
    seen.add(key);
    solutions.push(sol);
    if (solutions.length >= limit) break;
  }
  solutions.sort((a, b) => a.cost - b.cost);
  return solutions;
}

function decode(chosen, info, res) {
  const bySlot = {};
  const wineGrants = {};
  for (const id of chosen) {
    const i = info[id];
    if (!i) continue;
    if (i.kind === 'wine') {
      wineGrants[i.affix] = res ? Math.round(res[id]) : 1;
      continue;
    }
    if (!bySlot[i.slot]) bySlot[i.slot] = { gear: null, gems: [] };
    if (i.kind === 'gear') bySlot[i.slot].gear = i.variant;
    else {
      const si = i.socketIndex != null ? i.socketIndex : 0;
      bySlot[i.slot].gems[si] = i.gem;
    }
  }

  const slots = Object.keys(bySlot)
    .sort((a, b) => {
      const ia = SLOT_ORDER.indexOf(a), ib = SLOT_ORDER.indexOf(b);
      return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
    })
    .map(s => {
      const e = bySlot[s];
      const gear = e.gear;
      return {
        slot: s,
        gear: gear ? gear.gear : null,
        rarity: gear ? gear.rarity : null,
        built_in_affix: gear ? gear.built_in_affix : null,
        sockets: gear ? gear.sockets : [],
        gems: gear ? e.gems.map(g => g || null) : []
      };
    });

  let cost = 0;
  for (const id of chosen) {
    const i = info[id];
    if (i && (i.kind === 'gear' || i.kind === 'gem')) cost += i.cost || 0;
  }

  const capacityWarnings = [];
  for (const sl of slots) {
    if (!sl.gear) continue;
    const maxCap = RARITY_CAPACITY[sl.rarity];
    if (maxCap == null) continue;
    const cap = (sl.built_in_affix ? 1 : 0) + sl.sockets.reduce((a, sk) => a + (sk.tier || 1), 0);
    if (cap > maxCap) {
      capacityWarnings.push(sl.slot + ': ' + sl.gear + ' [' + sl.rarity + '] affix capacity ' + cap + ' exceeds rarity max ' + maxCap);
    }
  }

  const gr = Object.keys(wineGrants).sort().reduce((o, k) => { o[k] = wineGrants[k]; return o; }, {});
  return { slots, cost: Math.round(cost), capacityWarnings, wineGrants: gr };
}

function reachableAffixes(className, weapon) {
  const { gear, gemCatalog } = loadData();
  if (!WEAPONS_BY_CLASS[className] || !WEAPONS_BY_CLASS[className].includes(weapon)) return [];
  const valid = validAffixSet();
  const slots = ARMOR_SLOTS.concat([weapon]).concat(ACCESSORY_SLOTS);
  const set = new Set();
  for (const slot of slots) {
    for (const v of poolFor(gear, className, slot)) {
      if (v.built_in_affix && valid.has(v.built_in_affix)) set.add(v.built_in_affix);
      for (const sock of v.sockets) {
        for (const g of compatibleGems(gemCatalog, sock)) {
          if (g.affix1 && valid.has(g.affix1)) set.add(g.affix1);
          if (g.affix2 && valid.has(g.affix2)) set.add(g.affix2);
        }
      }
    }
  }
  return [...set];
}

// Only classes listed here are published/enabled in the UI. Add a class once
// you've finished its data. A class ALSO needs real gear data (built-in affix or
// socket in its own armor+weapon) to actually enable — so you can't accidentally
// turn on an empty class. Blackarrow is live (Seer, Sorcerer, Blackarrow).
const ENABLED_CLASSES = ['Seer', 'Sorcerer', 'Blackarrow'];

// A class is "ready" (enabled) only when it is in ENABLED_CLASSES AND its own
// class-specific armor + weapon gear actually carries a built-in affix or a
// socket. Shared Ring/Necklace accessories are ignored, so an empty class isn't
// falsely enabled.
function classComplete(className) {
  if (!ENABLED_CLASSES.includes(className)) return false;
  const { gear } = loadData();
  const weapons = WEAPONS_BY_CLASS[className] || [];
  const slots = ARMOR_SLOTS.concat(weapons);
  for (const s of slots) {
    for (const v of poolFor(gear, className, s)) {
      if (v.built_in_affix) return true;
      if (v.sockets && v.sockets.length > 0) return true;
    }
  }
  return false;
}

// Allowlist is public metadata for the UI / observability (e.g. to show which
// classes are gated vs. simply missing data).
function classGated(className) {
  return !ENABLED_CLASSES.includes(className);
}

// Equivalent of the old GET /api/meta.
function buildMeta() {
  const reachable = {};
  const complete = {};
  for (const cls of Object.keys(WEAPONS_BY_CLASS)) {
    for (const weapon of WEAPONS_BY_CLASS[cls]) {
      reachable[cls + '-' + weapon] = reachableAffixes(cls, weapon);
    }
    complete[cls] = classComplete(cls);
  }
  return {
    weaponsByClass: WEAPONS_BY_CLASS,
    slots: { armor: ARMOR_SLOTS, accessories: ACCESSORY_SLOTS },
    reachable,
    complete,
    wines: WINES
  };
}

export const classes = DATA.classes;
export const affixes = DATA.affixes;
export const meta = buildMeta();
export {
  generateBuild,
  generateMoreBuilds,
  buildSetKey,
  buildMeta,
  reachableAffixes,
  WEAPONS_BY_CLASS,
  WINES,
  SOL_LIMIT,
  ENABLED_CLASSES
};
